import { ListToolsRequest, Tool } from '@modelcontextprotocol/sdk/types.js';
import {
  GET_INSTRUMENTS_INFO_TOOL,
  GET_ORDERBOOK_TOOL,
  GET_TICKERS_TOOL,
  GET_KLINE_TOOL,
  GET_RECENT_TRADES_TOOL,
  GET_FUNDING_RATE_HISTORY_TOOL,
  PLACE_ORDER_TOOL,
  AMEND_ORDER_TOOL,
  CANCEL_ORDER_TOOL,
  GET_OPEN_CLOSED_ORDERS_TOOL,
  GET_ORDER_HISTORY_TOOL,
  GET_TRADE_HISTORY_TOOL,
  GET_POSITION_INFO_TOOL,
  SET_LEVERAGE_TOOL,
  GET_WALLET_BALANCE_TOOL,
  GET_ACCOUNT_INFO_TOOL,
} from '../tools';

export async function handleListTools(
  _request: ListToolsRequest,
): Promise<{ tools: Tool[] }> {
  return {
    tools: [
      GET_INSTRUMENTS_INFO_TOOL,
      GET_ORDERBOOK_TOOL,
      GET_TICKERS_TOOL,
      GET_KLINE_TOOL,
      GET_RECENT_TRADES_TOOL,
      GET_FUNDING_RATE_HISTORY_TOOL,
      PLACE_ORDER_TOOL,
      AMEND_ORDER_TOOL,
      CANCEL_ORDER_TOOL,
      GET_OPEN_CLOSED_ORDERS_TOOL,
      GET_ORDER_HISTORY_TOOL,
      GET_TRADE_HISTORY_TOOL,
      GET_POSITION_INFO_TOOL,
      SET_LEVERAGE_TOOL,
      GET_WALLET_BALANCE_TOOL,
      GET_ACCOUNT_INFO_TOOL,
    ],
  };
}
